# Generated by Django 3.2.7 on 2021-09-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo_Academico', models.CharField(max_length=25)),
                ('Fecha_inicio_Periodo', models.DateField()),
                ('Duracion_Ciclo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('Nombres', models.CharField(max_length=25)),
                ('Apellidos', models.CharField(max_length=25)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Edad', models.IntegerField()),
                ('sexoM', models.CharField(choices=[('H', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('PeriodoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.carrera')),
            ],
        ),
    ]
