# Generated by Django 3.2.7 on 2021-10-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_alter_estudiante_sexom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CicloEstudii', models.CharField(choices=[('P.Ciclo', 'Primer Ciclo'), ('S.Ciclo', 'SegundO Ciclo'), ('T.Ciclo', 'Tercer Ciclo')], max_length=1000)),
                ('MateriasPrimerC', models.BooleanField(choices=[('P.1', 'Legislacion'), ('P.1', 'Matematicas'), ('T.Ciclo', 'Tercer Ciclo')], default=False)),
                ('MateriasSegunC', models.BooleanField(choices=[('P.1', 'Legislacion'), ('P.1', 'Matematicas'), ('T.Ciclo', 'Tercer Ciclo')], default=False)),
            ],
        ),
    ]
