# Generated by Django 3.2.7 on 2021-10-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='MateriasSegunC',
        ),
        migrations.AddField(
            model_name='materias',
            name='MateriasPrimerC1',
            field=models.BooleanField(default=False, verbose_name='Legislacion'),
        ),
        migrations.AddField(
            model_name='materias',
            name='MateriasPrimerC2',
            field=models.BooleanField(default=False, verbose_name='Matematica'),
        ),
    ]
