# Generated by Django 3.2.7 on 2021-10-02 05:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_auto_20211001_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC1',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC2',
        ),
        migrations.AlterField(
            model_name='materias',
            name='CicloEstudii',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Legislacion', 'Legislacion'), ('matematicas', 'Matematicas'), ('Programacion', 'Programacion'), ('Base de Datos', 'Base de Datos')], max_length=1000),
        ),
    ]
