# Generated by Django 3.2.7 on 2021-10-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_auto_20211002_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='MateriasPrimerC1',
            field=models.BooleanField(default=False, verbose_name='Legislacion'),
        ),
        migrations.AddField(
            model_name='materias',
            name='MateriasPrimerC2',
            field=models.BooleanField(default=False, verbose_name='Matematica'),
        ),
        migrations.AddField(
            model_name='materias',
            name='MateriasPrimerC3',
            field=models.BooleanField(default=False, verbose_name='Diseño'),
        ),
        migrations.AddField(
            model_name='materias',
            name='MateriasPrimerC4',
            field=models.BooleanField(default=False, verbose_name='BD'),
        ),
        migrations.AddField(
            model_name='materias',
            name='MateriasPrimerC5',
            field=models.BooleanField(default=False, verbose_name='Fundamentos'),
        ),
        migrations.AddField(
            model_name='materias',
            name='MateriasSegundC1',
            field=models.BooleanField(default=False, verbose_name='Matematica'),
        ),
    ]
