# Generated by Django 3.2.7 on 2021-10-02 05:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_auto_20211002_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC1',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC2',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC3',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC4',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='MateriasPrimerC5',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='MateriasSegundC1',
        ),
        migrations.AlterField(
            model_name='materias',
            name='CicloEstudii',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Legislacion', 'Legislacion'), ('matematicas', 'Matematicas'), ('Programacion', 'Programacion'), ('Base de Datos', 'Base de Datos')], default=False, max_length=1000),
        ),
    ]
