# Generated by Django 3.2.7 on 2021-10-05 01:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0010_auto_20211004_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='PrimerCiclo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Matemáticas Discretas', 'Matemáticas Discretas'), ('Introducción al Desarrollo de Software', 'Introducción al Desarrollo de Software'), ('Fundamentos de la Programación', 'Fundamentos de la Programación'), ('Análisis y Diseño de Sistemas', 'Análisis y Diseño de Sistemas'), ('Ingles I', 'Ingles I'), ('Desarrollo del Pensamiento', 'Desarrollo del Pensamiento')], default=False, max_length=1000),
        ),
    ]
