# Generated by Django 3.2.7 on 2021-10-05 01:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0011_alter_estudiante_primerciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='CuartoCiclo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Estadística Descriptiva', 'Estadística Descriptiva'), ('Legislación Informática', 'Legislación Informática'), ('Programación de Aplicaciones Web', 'Programación de Aplicaciones Web'), ('Desarrollo de Aplicaciones Moviles', 'Desarrollo de Aplicaciones Moviles'), ('Ingles IV', 'Ingles IV'), ('Diversidad Cultural', 'Diversidad Cultural')], default=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='QuintoCiclo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Proyecto de Titulación', 'Proyecto de Titulación'), ('Emprendimientos', 'Emprendimientos'), ('Auditoria Informática', 'Auditoria Informática'), ('Tendencias Actuales de Programación', 'Tendencias Actuales de Programación'), ('Calidad de Software', 'Calidad de Software'), ('Fundamentos de Software y Conectividad', 'Fundamentos de Software y Conectividad'), ('Ética Profesional', 'Ética Profesional')], default=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='SegundoCiclo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Algebra y Trigonometría', 'Algebra y Trigonometría'), ('Base de Datos', 'Base de Datos'), ('Programación Orientada a Objetos', 'Programación Orientada a Objetos'), ('Metodologías de Desarrollo de Software', 'Metodologías de Desarrollo de Software'), ('Ingles II', 'Ingles II'), ('Lenguaje y Comunicación', 'Lenguaje y Comunicación')], default=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='TercerCiclo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cálculo Diferencial e Integral', 'Algebra y Trigonometría'), ('Fundamentos de la Administración', 'Base de Datos'), ('Programación Visual', 'Programación Orientada a Objetos'), ('Base de Datos Avanzada', 'Base de Datos Avanzada'), ('Diseño de Interfaz', 'Diseño de Interfaz'), ('Ingles III', 'Ingles III')], default=False, max_length=1000),
        ),
    ]
